E-commerce/Pages/Basket.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using E_commerce.DataAPI;
using E_commerce.Service;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace E_commerce.Pages
{
    public class AllProductClass
    {
        public Product productfromapi { get; set; }

        public Model.Products productfromjson { get; set; }
    }

    public class BasketModel : BaseModel
    {
        public JsonFileService fileservice { get; set; }

        public ProductsAPIService apiService { get; set; }

        public List<AllProductClass> productsList { get; set; } = new List<AllProductClass>();

        public Dictionary<string, double> SessionDic { get; set; } = new Dictionary<string, double>();

        public double subtotal { get; set; }

        public BasketModel(JsonFileService jsonFileService, ProductsAPIService productsAPIService)
        {
            fileservice = jsonFileService;
            apiService = productsAPIService;
        }

        public async Task OnGetAsync()
        {
            var apidata = await apiService.GetProductsFromAPI();
            var jsondata = fileservice.GetAll();

            foreach (var each in HttpContext.Session.Keys)
            {
                var productPrice = Convert.ToDouble(HttpContext.Session.GetString(each));
                SessionDic[each] = productPrice;
                if (apidata.Product.FirstOrDefault(product => product.Title == each) != null)
                {
                    var newclass = new AllProductClass();
                    var product = apidata.Product.First(product => product.Title == each);
                    newclass.productfromapi = product;
                    productsList.Add(newclass);
                }
                else
                {
                    var newclass = new AllProductClass();
                    var product = jsondata.First(product => product.Title == each);
                    newclass.productfromjson = product;
                    productsList.Add(newclass);
                }
            }
            foreach (var each in HttpContext.Session.Keys)
            {
                var productPrice = Convert.ToDouble(HttpContext.Session.GetString(each));
                subtotal += productPrice;
            }
        }

        public IActionResult OnPostDeleteProduct(string title)
        {
            HttpContext.Session.Remove(title);
            return RedirectToPage("RedirectPage");
        }

        public IActionResult OnPostDeselectAll()
        {
            HttpContext.Session.Clear();
            return RedirectToPage("RedirectPage");
        }
    }
}

E-commerce/Pages/BestSeller.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using E_commerce.DataAPI;
using E_commerce.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace E_commerce.Pages
{
    public class BestSellerModel : BaseModel
    {
        public IEnumerable<Product> products { get; private set; }

        public IEnumerable<Product> SmartPhones { get; set; }

        public IEnumerable<Product> LapTops { get; set; }

        public IEnumerable<Product> Fragrances { get; set; }

        public IEnumerable<Product> Skincare { get; set; }

        public IEnumerable<Product> Groceries { get; set; }

        public IEnumerable<Product> HomeDecoration { get; set; }

        private readonly ILogger<BestSellerModel> _logger;
        public ProductsAPIService apiService;

        public BestSellerModel(ProductsAPIService ApiService, ILogger<BestSellerModel> logger)
        {
            _logger = logger;
            apiService = ApiService;
    }

        public async Task OnGet()
        {
            var data = await apiService.GetProductsFromAPI();
            products = data.Product;
            SmartPhones = from each in products where each.Category == "smartphones" select each;
            LapTops = from each in products where each.Category == "laptops" select each;
            Fragrances = from each in products where each.Category == "fragrances" select each;
            Skincare = from each in products where each.Category == "skincare" select each;
            Groceries = from each in products where each.Category == "groceries" select each;
            HomeDecoration = from each in products where each.Category == "home-decoration" select each;
        }
    }
}

E-commerce/Pages/Clothing.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using E_commerce.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace E_commerce.Pages
{
    public class ColthingModel : BaseModel
    {
        public void OnGet()
        {
        }
    }
}

E-commerce/Pages/Clothing/MenClothing.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using E_commerce.DataAPI;
using E_commerce.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace E_commerce.Pages
{
    public class MenClothingModel : BaseModel
    {

        public JsonFileService jsonFileService;

        public IEnumerable<Model.Products> MenClothesFromJson { get; set; }

        public MenClothingModel(JsonFileService fileService)
        {
            jsonFileService = fileService;
            
        }
            public void OnGet()
        {
            MenClothesFromJson = jsonFileService.GetMenClothes();

        }
    }
}

E-commerce/Pages/Clothing/WomenClothing.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using E_commerce.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace E_commerce.Pages
{
    public class WomenClothingModel : BaseModel
    {

        public JsonFileService jsonfileservice;

        public IEnumerable<Model.Products> WomenClothingFromJson { get; private set; }

        public WomenClothingModel(JsonFileService fileService)
        {
            jsonfileservice = fileService;
        }
            public void OnGet()
        {
            WomenClothingFromJson = jsonfileservice.GetWomenClothes();
        }
    }
}

E-commerce/Pages/ConfirmAdded.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using E_commerce.DataAPI;
using E_commerce.Service;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace E_commerce.Pages
{
    public static class SessionExtensions
    {
        public static double? GetDouble(this ISession session, string key)
        {
            var data = session.Get(key);
            if (data == null)
            {
                return null;
            }
            return BitConverter.ToDouble(data, 0);
        }

        public static void SetDouble(this ISession session, string key, double value)
        {
            session.Set(key, BitConverter.GetBytes(value));
        }
    }

    public class ConfirmAddedModel : BaseModel
    {
        public JsonFileService fileservice { get; set; }

        public ProductsAPIService apiService { get; set; }

        public Product product { get; set; }

        public IEnumerable<Product> productList { get; set; }

        public Model.Products products { get; set; }

        public double subtotal { get; set; }

        public ConfirmAddedModel(JsonFileService jsonFileService, ProductsAPIService productsAPIService)
        {
            fileservice = jsonFileService;
            apiService = productsAPIService;
        }

        public async Task OnGetAsync(string name, double price)
        {            
            var jsonData = fileservice.GetAll();
            var apiData = await apiService.GetProductsFromAPI();
            if(apiData.Product.FirstOrDefault(each => each.Title == name) != null)
            {
                product = apiData.Product.First(each => each.Title == name);
                HttpContext.Session.SetString(product.Title, price.ToString());
            }
            else
            {
                products = jsonData.First(each => each.Title == name);
                HttpContext.Session.SetString(products.Title, price.ToString());

            }
            foreach(var each in HttpContext.Session.Keys)
            {
                var productPrice = Convert.ToDouble(HttpContext.Session.GetString(each));
                subtotal += productPrice;
            }

            productList = apiData.Product.Take(6);
        }
    }
}

E-commerce/Pages/Electronics.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using E_commerce.DataAPI;
using E_commerce.Model;
using E_commerce.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace E_commerce.Pages
{
    public class ElectronicsModel : BaseModel
    {

        public JsonFileService productService;

        public ProductsAPIService productAPIService;

        public IEnumerable<Product> SmartPhones { get; set; }

        public IEnumerable<Product> LapTops { get; set; }

        public IEnumerable<Model.Products> EletronicsFromJson { get; private set; }

        public IEnumerable<Product> productsFromAPI { get; private set; }

        public ElectronicsModel(JsonFileService fileService, ProductsAPIService apiService)
        {
            productService = fileService;
            productAPIService = apiService;

        }
        public async Task OnGet()
        {
            EletronicsFromJson = productService.GetElectronics();
            var allData = await productAPIService.GetProductsFromAPI();
            SmartPhones = from each in allData.Product where each.Category == "smartphones" select each;
            LapTops = from each in allData.Product where each.Category == "laptops" select each;
        }
    }
}

E-commerce/Pages/Electronics/Accessories.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using E_commerce.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace E_commerce.Pages
{
    public class AccessoriesModel : BaseModel
    {

        public JsonFileService productService;

        public IEnumerable<Model.Products> Accessories { get; private set; }

        public AccessoriesModel(JsonFileService fileService)
        {
            productService = fileService;
        }

        public void OnGet()
        {
            Accessories = productService.GetElectronics();
        }
    }
}

E-commerce/Pages/Electronics/Laptops.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using E_commerce.DataAPI;
using E_commerce.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace E_commerce.Pages
{
    public class LaptopsModel : BaseModel
    {
        public ProductsAPIService productAPIService;

        public IEnumerable<Product> Laptops { get; set; }

        public LaptopsModel(ProductsAPIService apiService)
        {
            productAPIService = apiService;
        }

        public async Task OnGet()
        {
            var allData = await productAPIService.GetProductsFromAPI();
            Laptops = from each in allData.Product where each.Category == "laptops" select each;
        }
    }
}

E-commerce/Pages/Electronics/SmartPhone.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using E_commerce.DataAPI;
using E_commerce.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace E_commerce.Pages
{
    public class SmartPhoneModel : BaseModel
    {
        public ProductsAPIService productAPIService;

        public IEnumerable<Product> SmartPhones { get; set; }

        public SmartPhoneModel(ProductsAPIService apiService)
        {
            productAPIService = apiService;
        }

        public async Task OnGet()
        {
            var allData = await productAPIService.GetProductsFromAPI();
            SmartPhones = from each in allData.Product where each.Category == "smartphones" select each;
        }
    }
}

E-commerce/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace E_commerce.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

E-commerce/Pages/Fragrance.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using E_commerce.DataAPI;
using E_commerce.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace E_commerce.Pages
{
    public class FragranceModel : BaseModel
    {
        
        public IEnumerable<Product> FragranceFromAPI { get; set; }

        public ProductsAPIService APIService;

        public FragranceModel(ProductsAPIService apiservice)
        {
            APIService = apiservice;
        }
        public async Task OnGet()
        {
            var allData = await APIService.GetProductsFromAPI();
            FragranceFromAPI = from data in allData.Product where data.Category == "fragrances" select data;
        }
    }
}

E-commerce/Pages/HomeDecoration.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace E_commerce.Pages
{
    public class HomeDecorationModel : BaseModel
    {
        public void OnGet()
        {
        }
    }
}

E-commerce/Pages/SearchResult.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using E_commerce.DataAPI;
using E_commerce.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace E_commerce.Pages
{

    public class newClass
    {
        public Product apiData { get; set; }

        public Model.Products jsonData { get; set; }

    }

    public class SearchResultModel : BaseModel
    {
        public JsonFileService jsonfileservice;

        public ProductsAPIService productapiservice;

        public IEnumerable<Product> ProductsFromAPI { get; set; }


        public IEnumerable<Model.Products> ProductsFromJson { get; set; }

        public IEnumerable<Product> AllProductsFromAPI { get; set; }

        public IEnumerable<Model.Products> AllProductsFromJson { get; set; }

        public string SearchValue { get; set; }

        public Dictionary<string, string> data { get; set; }

        public int PageNumber { get; set; }

        public int currentPage { get; set; }

        public newClass[] theArray { get; set; }

        public IEnumerable<newClass> dataToShow { get; set; }

        public SearchResultModel(JsonFileService fileservice, ProductsAPIService apiservice)
        {
            jsonfileservice = fileservice;
            productapiservice = apiservice;
        }

        public async Task OnGet(Dictionary<string, string> param)
        {
            data = param;
            SearchValue = data.First().Value;
            var allDataFromAPI = await productapiservice.GetProductsFromAPI();            
            AllProductsFromAPI = from each in allDataFromAPI.Product where each.Title.ToLower().Contains(SearchValue.ToLower()) select each;            
            var allDataFromJson = jsonfileservice.GetAll();
            AllProductsFromJson = from each in allDataFromJson where each.Title.ToLower().Contains(SearchValue.ToLower()) select each;
            PageNumber = (AllProductsFromAPI.Count() + AllProductsFromJson.Count()) / 10;
            theArray = new newClass[AllProductsFromAPI.Count() + AllProductsFromJson.Count()];
            for (var i = 0; i < AllProductsFromAPI.Count(); i++)
            {
                var newObj = new newClass();
                newObj.apiData = AllProductsFromAPI.ElementAt(i);
                theArray[i] = newObj;
            }
            for (var i = 0; i < AllProductsFromJson.Count(); i++)
            {
                var newObj = new newClass();
                newObj.jsonData = AllProductsFromJson.ElementAt(i);
                theArray[i + AllProductsFromAPI.Count()] = newObj;
            }

            dataToShow = from each in theArray select each;

            if (param.ContainsKey("pageNum"))
            {
                string page = data.Last().Value;
                dataToShow = dataToShow.Skip((Int32.Parse(page) - 1) * 10).Take(10);
            }
            else
            {
                dataToShow = dataToShow.Take(10);
            }
        }

        public IActionResult OnPostSwitchPage(int pageNum, string input)
        {
            var paramToPass = new Dictionary<string, string>
            {
                { "input", input},
                { "pageNum", pageNum.ToString() }
            };

            return RedirectToPage("SearchResult", paramToPass);

        }
    }
}

E-commerce/Pages/Basket.cshtml
@page
@model E_commerce.Pages.BasketModel
@using Microsoft.AspNetCore.Http;
@{
}
<body style="background-color:#EAEDED !important;">
    @if (HttpContext.Session.Keys.Count() == 0)
    {


        <div style="background-color:white;margin-left:3rem; margin-right:3rem;">
            <div style="padding:1.5rem;font-size: 14px; line-height: 20px;">
                @*Show this instead if the basket is empty*@
                <h1 style="font-weight: 400; font-size: 28px; line-height: 36px;">
                    Your Shopping Cart is empty.
                </h1>
                <p>
                    Your shopping basket lives to serve. Give it purpose – fill it with groceries, clothing, household supplies, electronics and more.
                    Continue shopping on the Haystore homepage, learn about today's deals.
                </p>
            </div>
        </div>
    }
    else
    {
        <div style="margin-left: 18px; margin-right: 18px; margin-top: 1.5rem; background-color: white;">
            <div style="padding-left: 20px; padding-right: 20px;">
                <div style="padding-top:20px; font-size: 14px; line-height: 20px; display:flex; flex-direction:column;">
                    <h1 style="font-weight: 400; font-size: 28px; line-height: 36px;">
                        Shopping Basket
                    </h1>
                    <form asp-page-handler="DeselectAll">
                        <button style="color: #007185; margin-bottom: 0px; background-color: white; border-style: none; font-size:14px">
                            Remove all items
                        </button>
                    </form>
                    <p style="align-self: end; color: #565959;margin-bottom:0;">
                        Price
                    </p>
                </div>
                <hr style="margin-top:0;" />
                <div>
                    @foreach (var each in Model.productsList)
                    {
                        if (each.productfromapi == null)
                        {
                            <div style="display: flex; flex-direction: row; margin-top: 16px; margin-bottom: 12px">
                                <div style="height:180px !important; width:180px !important">
                                    <img src="@each.productfromjson.Img" style="height:100%; width:100%" />

                                </div>
                                <div style="margin-left:10px; width:100%; display:flex; flex-direction:column; justify-content:space-between">
                                    <div style="display:flex; flex-direction:row; justify-content:space-between; width:100%">

                                        <h1 style="font-size:18px;">
                                            @each.productfromjson.Title
                                        </h1>
                                        <h1 style="font-size:18px;">
                                            £@Convert.ToDouble(HttpContext.Session.GetString(each.productfromjson.Title)).ToString("#.00")
                                        </h1>
                                    </div>
                                    <ul style="font-size:12px; color:#565959; list-style:none; padding-inline-start:0px;">
                                        <li style="color:#007600; padding-top:12px">
                                            in stock
                                        </li>
                                        <li style=" padding-top:12px; ">
                                            Dispatched from and sold by Haystore
                                        </li>
                                        <li style=" padding-top:12px; ">
                                            Eligible for FREE Shipping
                                        </li>
                                    </ul>
                                    <form asp-page-handler="DeleteProduct" asp-route-title="@each.productfromjson.Title" style="margin-top:auto">
                                        <button style="background-color: white; border-style: none; color: #007185 !important; font-size:14px">
                                            Delete
                                        </button>
                                    </form>
                                </div>
                            </div>
                            <hr style="width:100%; margin-bottom:0px;" />

                        }
                        else
                        {
                            <div style="display:flex; flex-direction:row;margin-top:16px; margin-bottom:12px">
                                <div style="height:180px !important; width:180px !important">
                                    <img src="@each.productfromapi.Thumbnail" style="height:100%; width:100%" />
                                </div>
                                <div style="margin-left:10px; width:100%; display:flex; flex-direction:column; justify-content:space-between">
                                    <div style="display:flex; flex-direction:row; justify-content:space-between; width:100%">
                                        <h1 style="font-size:18px;">
                                            @each.productfromapi.Title
                                        </h1>
                                        <h1 style="font-size:18px;">
                                            £@Convert.ToDouble(HttpContext.Session.GetString(each.productfromapi.Title)).ToString("#.00")
                                        </h1>
                                    </div>

                                    <ul style="font-size:12px; color:#565959; list-style:none; padding-inline-start:0px;">
                                        <li style="color:#007600; padding-top:12px;">
                                            in stock
                                        </li>
                                        <li style=" padding-top:12px; ">
                                            Dispatched from and sold by Haystore
                                        </li>
                                        <li style=" padding-top:12px; ">
                                            Eligible for FREE Shipping
                                        </li>
                                    </ul>
                                    <form asp-page-handler="DeleteProduct" asp-route-title="@each.productfromapi.Title" style="margin-top:auto">
                                        <button style="background-color: white; border-style: none; color: #007185 !important; font-size:14px">
                                            Delete
                                        </button>
                                    </form>
                                </div>
                            </div>
                            <hr style="width:100%; margin-bottom:0px;" />
                        }
                    }
                </div>
                <p style="font-size:18px; text-align:end; padding-bottom:20px">
                    Subtotal (@(HttpContext.Session.Keys.Count()) items):<span style="font-weight:bold;"> £@Model.subtotal</span>
                </p>
            </div>

        </div>
    }
</body>

E-commerce/Pages/Clothing.cshtml
@page
@model E_commerce.Pages.ColthingModel
@{
}

<p style="font-size: 28px; line-height:36px; font-weight:700; text-align:center; margin-top: 60px">
    Categories
</p>
<div class="d-flex justify-content-center" style="gap:120px; margin-top:5%">
    <div style="width: 199px; height: 278px; text-align:center; display:flex; flex-direction:column; align-items:center">
        <div style="height: 180px; width: 180px; border-radius: 100%; display: flex; justify-content: center; align-items: center; flex-direction: column; background: #FFEFF1">
            <a asp-page="./Clothing/MenClothing" style="">
                <img style="height:130px; width:130px;" src="Images/kindpng_3339588.png" />
            </a>
        </div>
        <p>
            Mens
        </p>

    </div>
    <div style="width: 199px; height: 278px; text-align:center; display:flex; flex-direction:column; align-items:center">
        <div style="height: 180px; width: 180px; border-radius: 100%; display: flex; justify-content: center; align-items: center; flex-direction: column; background: #FFEFF1">
            <a asp-page="./Clothing/WomenClothing" style="">
                <img style="height:130px; width:130px;" src="Images/kindpng_633936.png" />
            </a>
        </div>
        <p>
            Womens
        </p>

    </div>

</div>

E-commerce/Pages/HomeDecoration.cshtml
@page
@model E_commerce.Pages.HomeDecorationModel
@{
}

E-commerce/Pages/Index.cshtml
@page
@model E_commerce.Pages.IndexModel
@{
}

<div style="margin-left:30px">
    <h1 style="margin-bottom:60px">This is a e-commerce website's design is based on Amazon's Website.</h1>
    <p style="font-size:24px">Welcome to the starting point of my .Net Journey    <span style="font-size:64px; font-weight:bold">HayStore</span></p>
</div>

E-commerce/Pages/RedirectPage.cshtml
@page
@model E_commerce.Pages.RedirectPageModel
@{
}
<h1>
    Redirecting
</h1>

E-commerce/Pages/SearchResult.cshtml
@page
@model E_commerce.Pages.SearchResultModel
@{
    bool empty = Model.dataToShow.Count() == 0;
}

<body style="background-color:#EAEDED !important;">

    @if (empty)
    {
        <h1 style="text-align: center; background-color: white; margin-bottom: 0; margin-left: 3rem; margin-right: 3rem; padding-top:1.5rem; padding-bottom:1.5rem;">
            No result for @Model.SearchValue
        </h1>
    }
    else
    {
        <h1 style="text-align: center; background-color: white; margin-bottom: 0; margin-left: 3rem; margin-right: 3rem; padding-top:1.5rem; padding-bottom:1.5rem;">Search Result</h1>

    }

    @foreach (var obj in Model.dataToShow)
    {
        if (obj.apiData != null)
        {
            var each = obj.apiData;

            <div style="background-color: white; margin-left: 3rem; margin-right: 3rem;">
                <div style=" display: flex; flex-direction: row; margin:1rem;">
                    <a style="width:25%; display:flex; justify-content:center" asp-page="/ShowProduct" asp-route-name="@each.Title">
                        <img src="@each.Thumbnail" style="width:100%; height:240px; align-self:center; " />
                    </a>
                    <div style="width:75%; margin:1rem;">
                        <a style="font-size: 2.5rem ;font-weight: bold; color:black; text-decoration:none" asp-page="/ShowProduct" asp-route-name="@each.Title">
                            @each.Title
                        </a>
                        <p>
                            @for (var i = 0.5; i < 5; i++)
                            {
                                <span class="@(i <= each.Rating ? "fa fa-star checked rating " : "far fa-star rating")"></span>
                            }
                        </p>
                        <p>
                            @each.Description
                        </p>
                        <a style="font-size:28px; color:black; text-decoration:none" asp-page="/ShowProduct" asp-route-name="@each.Title">
                            £@each.Price
                        </a>
                        <p style="font-size:14px">
                            Available instantly
                        </p>
                    </div>
                </div>
            </div>
        }
        else
        {
            var each = obj.jsonData;
            <div style="background-color: white; margin-left: 3rem; margin-right: 3rem;">
                <div style=" display: flex; flex-direction: row; margin:1rem;">

                    <a style="width:25%; display:flex; justify-content:center" asp-page="/ShowProduct" asp-route-name="@each.Title">
                        <img src="@each.Img" style="width:100%; height:240px; align-self:center; " />
                    </a>
                    <div style="width:75%; margin:1rem;">
                        <a style="font-size: 2.5rem ;font-weight: bold; color:black; text-decoration:none" asp-page="/ShowProduct" asp-route-name="@each.Title">
                            @each.Title
                        </a>
                        <p>
                            @for (var i = 0; i < 5; i++)
                            {
                                <span class="@(i <= each.Rating.rate ? "fa fa-star checked rating " : "far fa-star rating")"></span>
                            }
                        </p>
                        <p>
                            @each.Description
                        </p>
                        <a style="font-size:28px; color:black; text-decoration:none" asp-page="/ShowProduct" asp-route-name="@each.Title">
                            £@each.Price
                        </a>
                        <p style="font-size:14px">
                            Available instantly
                        </p>
                    </div>
                </div>
            </div>
        }
    }


    <div style="display:flex; flex-direction:row; justify-content:center">
        @for (var i = 0; i <= Model.PageNumber; i++)
        {
            <form asp-page-handler="SwitchPage" asp-route-pageNum="@(i+1)" asp-route-input="@Model.SearchValue">
                <button style="margin-right:12px; border-style:none;">@(i + 1)</button>
            </form>
        }
    </div>

</body>